In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [2]:
data = pd.read_csv(r'D:\Krish_Naik\Python\Deep Learning\Regression\Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
## Preprocessing the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
## Encoding the categorical data
labelencoder = LabelEncoder()
data['Gender'] = labelencoder.fit_transform(data['Gender'])
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [6]:
### One hot encoding the 'Geography' column
onehotencoder = OneHotEncoder(handle_unknown='ignore')
geography = onehotencoder.fit_transform(data['Geography'].values.reshape(-1,1)).toarray()
geography_df = pd.DataFrame(geography, columns=onehotencoder.get_feature_names_out(['Geography']))
geography_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [8]:
data =pd.concat([data.drop('Geography',axis=1),geography_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [9]:
#### Splitting the dataset into the Training set and Test set
X =data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [10]:
### Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
### Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
### Save the encoders and scaler for future use
with open('labelencoder.pkl', 'wb') as file:
    pickle.dump(labelencoder, file)

with open('onehotencoder.pkl', 'wb') as file:
    pickle.dump(onehotencoder, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [14]:
### ANN Regression Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1)  # Output layer for regression
])

## Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

d:\Krish_Naik\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
### Train the model
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

## Set up TensorBoard callback
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
## Set up EarlyStopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [18]:
#Train the model
history = model.fit(X_train, y_train,
                    validation_data=(X_test, y_test), 
                    validation_split=0.2, epochs=100,
                    batch_size=32,
                    callbacks=[early_stopping, tensorboard_callback]
                    )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100377.6797 - mae: 100377.6797 - val_loss: 98513.1172 - val_mae: 98513.1172
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99584.4062 - mae: 99584.4062 - val_loss: 96898.5703 - val_mae: 96898.5703
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96745.8125 - mae: 96745.8125 - val_loss: 92755.6562 - val_mae: 92755.6562
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91175.8438 - mae: 91175.8438 - val_loss: 85871.4375 - val_mae: 85871.4375
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83118.7422 - mae: 83118.7422 - val_loss: 77116.9219 - val_mae: 77116.9219
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 73858.5078 - mae: 73858.5078 - val_loss: 68186.6094 - val_mae: 68186.6094
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 65031.6289 - mae: 65031.6289 - val_loss: 60600.5234 - val_mae: 60600.5234
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 58163.6875 - mae: 58163.6875 - val_loss: 55351.4805 - val_mae: 55351.4805
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53786.4922 - mae: 53786.4922 - val_loss: 52482.3867 - val_mae: 52482.3867
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51518.7461 - mae: 51518.7461 - val_loss: 51292.8906 - val_mae: 51292.8906
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50630.7031 - mae: 50630.7031 - val_loss: 50970.7578 - val_mae: 50970.7578
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50319.6172 - mae: 50319.6172 - val_loss: 50846.8281 - val_mae: 50846.8281
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50187.7305 - mae: 50187.7305 - val_loss: 50779.8555 - val_mae: 50779.8555
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50108.0039 - mae: 50108.0039 - val_loss: 50736.1719 - val_mae: 50736.1719
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50050.2617 - mae: 50050.2617 - val_loss: 50699.5898 - val_mae: 50699.5898
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50003.2148 - mae: 50003.2148 - val_loss: 50655.1641 - val_mae: 50655.1641
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49961.9102 - mae: 49961.9102 - val_loss: 50625.4336 - val_mae: 50625.4336
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49925.8906 - mae: 49925.8906 - val_loss: 50600.8281 - val_mae: 50600.8281
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49895.4492 - mae: 49895.4492 - val_loss: 50586.7969 - val_mae: 50586.7969
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49862.7188 - mae: 49862.7188 - val_loss: 50560.3906 - val_mae: 50560.3906
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49833.7656 - mae: 49833.7656 - val_loss: 50535.8203 - val_mae: 50535.8203
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49809.0938 - mae: 49809.0938 - val_loss: 50516.5156 - val_mae: 50516.5156
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49787.0117 - mae: 49787.0117 - val_loss: 50502.6680 - val_mae: 50502.6680
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49766.7109 - mae: 49766.7109 - val_loss: 50492.8047 - val_mae: 50492.8047
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49748.0430 - mae: 49748.0430 - val_loss: 50482.6016 - val_mae: 50482.6016
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49728.4023 - mae: 49728.4023 - val_loss: 50465.0703 - val_mae: 50465.0703
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49709.1211 - mae: 49709.1211 - val_loss: 50461.9141 - val_mae: 50461.9141
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49696.2383 - mae: 49696.2383 - val_loss: 50450.7617 - val_mae: 50450.7617
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49681.6133 - mae: 49681.6133 - val_loss: 50443.7227 - val_mae: 50443.7227
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49665.7539 - mae: 49665.7539 - val_loss: 50430.3242 - val_mae: 50430.3242
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49652.0742 - mae: 49652.0742 - val_loss: 50422.7031 - val_mae: 50422.7031
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49639.7148 - mae: 49639.7148 - val_loss: 50423.0078 - val_mae: 50423.0078
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49627.4922 - mae: 49627.4922 - val_loss: 50412.5664 - val_mae: 50412.5664
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49615.5000 - mae: 49615.5000 - val_loss: 50398.1562 - val_mae: 50398.1562
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49603.5898 - mae: 49603.5898 - val_loss: 50399.3672 - val_mae: 50399.3672
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49591.8516 - mae: 49591.8516 - val_loss: 50395.2422 - val_mae: 50395.2422
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49581.9648 - mae: 49581.9648 - val_loss: 50390.4141 - val_mae: 50390.4141
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49568.7109 - mae: 49568.7109 - val_loss: 50393.3359 - val_mae: 50393.3359
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49562.1641 - mae: 49562.1641 - val_loss: 50399.5742 - val_mae: 50399.5742
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49550.7695 - mae: 49550.7695 - val_loss: 50382.7695 - val_mae: 50382.7695
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49544.1797 - mae: 49544.1797 - val_loss: 50379.6094 - val_mae: 50379.6094
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49535.8320 - mae: 49535.8320 - val_loss: 50395.7148 - val_mae: 50395.7148
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49530.1211 - mae: 49530.1211 - val_loss: 50387.4570 - val_mae: 50387.4570
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49520.2578 - mae: 49520.2578 - val_loss: 50381.4688 - val_mae: 50381.4688
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49512.7812 - mae: 49512.7812 - val_loss: 50389.3594 - val_mae: 50389.3594
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49502.6641 - mae: 49502.6641 - val_loss: 50376.9688 - val_mae: 50376.9688
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49497.7227 - mae: 49497.7227 - val_loss: 50372.1758 - val_mae: 50372.1758
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49489.5039 - mae: 49489.5039 - val_loss: 50381.1328 - val_mae: 50381.1328
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49481.8867 - mae: 49481.8867 - val_loss: 50383.5859 - val_mae: 50383.5859
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49477.8750 - mae: 49477.8750 - val_loss: 50385.4531 - val_mae: 50385.4531
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49468.4688 - mae: 49468.4688 - val_loss: 50383.7461 - val_mae: 50383.7461
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49460.2422 - mae: 49460.2422 - val_loss: 50376.0742 - val_mae: 50376.0742
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49458.2148 - mae: 49458.2148 - val_loss: 50375.5547 - val_mae: 50375.5547
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49451.4453 - mae: 49451.4453 - val_loss: 50368.5234 - val_mae: 50368.5234
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49447.8711 - mae: 49447.8711 - val_loss: 50377.7852 - val_mae: 50377.7852
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49437.4219 - mae: 49437.4219 - val_loss: 50374.6836 - val_mae: 50374.6836
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49432.3906 - mae: 49432.3906 - val_loss: 50382.9062 - val_mae: 50382.9062
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49427.5742 - mae: 49427.5742 - val_loss: 50376.2422 - val_mae: 50376.2422
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49423.5430 - mae: 49423.5430 - val_loss: 50367.4883 - val_mae: 50367.4883
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49419.7969 - mae: 49419.7969 - val_loss: 50374.4688 - val_mae: 50374.4688
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49412.3086 - mae: 49412.3086 - val_loss: 50359.7891 - val_mae: 50359.7891
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49408.8672 - mae: 49408.8672 - val_loss: 50372.1133 - val_mae: 50372.1133
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49403.0781 - mae: 49403.0781 - val_loss: 50370.2031 - val_mae: 50370.2031
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49396.4922 - mae: 49396.4922 - val_loss: 50373.5742 - val_mae: 50373.5742
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49396.3984 - mae: 49396.3984 - val_loss: 50375.4922 - val_mae: 50375.4922
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49389.0000 - mae: 49389.0000 - val_loss: 50373.9727 - val_mae: 50373.9727
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49383.5938 - mae: 49383.5938 - val_loss: 50377.3711 - val_mae: 50377.3711
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49381.9766 - mae: 49381.9766 - val_loss: 50368.6875 - val_mae: 50368.6875
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49376.9766 - mae: 49376.9766 - val_loss: 50373.2891 - val_mae: 50373.2891
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49373.9023 - mae: 49373.9023 - val_loss: 50365.3672 - val_mae: 50365.3672
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49370.0938 - mae: 49370.0938 - val_loss: 50366.7695 - val_mae: 50366.7695

In [19]:
### Load extention tensorboard
%load_ext tensorboard

In [21]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 10656), started 0:00:18 ago. (Use '!kill 10656' to kill it.)

In [22]:
### Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 50359.7891 - mae: 50359.7891
Test Loss: 50359.7890625, Test MAE: 50359.7890625

In [23]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.