In [2]:
import gensim 
from gensim.models import word2vec, keyedvectors

In [3]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king=wv['king']

In [4]:
vec_king.shape

(300,)

In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [6]:
import pandas as pd
messages = pd.read_csv(r"D:\Krish_Naik\Python\NLP For ML\uci_sms_spam_mock.csv",sep=',')

In [7]:
messages

     label                                            message
0      ham                 Please send the report by evening.
1      ham                           Can you check this file?
2      ham                           Can you check this file?
3      ham                          Call me when you're free.
4      ham                            Let's have lunch today.
...    ...                                                ...
5567   ham                      Hey, are we meeting tomorrow?
5568   ham                           Can you check this file?
5569  spam  Congratulations! You have won a free ticket. C...
5570  spam  Congratulations! You have won a free ticket. C...
5571  spam           Exclusive offer just for you. Click now.

[5572 rows x 2 columns]

In [8]:
import re 
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ranje\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [10]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.split()
    review = [
        lemma.lemmatize(word) 
        for word in review
        ]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['Please send the report by evening',
 'Can you check this file',
 'Can you check this file',
 'Call me when you re free',
 'Let s have lunch today',
 'Can you check this file',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Claim your free voucher today',
 'Can you check this file',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Please send the report by evening',
 'Let s have lunch today',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Let s have lunch today',
 'Please send the report by evening',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Exclusive offer just for you Click now',
 'Congratulations You have won a free ticket Call now',
 'Claim your free voucher today',
 'Can you check this file',
 'Claim your free voucher today',
 'Let s have lunch today',
 'You have been selected for a reward',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Please send the report by evening',
 'Please send the report by evening',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Let s have lunch today',
 'Can you check this file',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'Win cash prize now',
 'Win cash prize now',
 'Claim your free voucher today',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'Let s have lunch today',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Can you check this file',
 'Can you check this file',
 'Let s have lunch today',
 'You have been selected for a reward',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'Can you check this file',
 'Call me when you re free',
 'Win cash prize now',
 'Let s have lunch today',
 'Call me when you re free',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Call me when you re free',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Let s have lunch today',
 'Congratulations You have won a free ticket Call now',
 'Please send the report by evening',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Call me when you re free',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'Please send the report by evening',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'Please send the report by evening',
 'Win cash prize now',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Let s have lunch today',
 'Call me when you re free',
 'Call me when you re free',
 'Let s have lunch today',
 'Can you check this file',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'You have been selected for a reward',
 'Win cash prize now',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'You have been selected for a reward',
 'Win cash prize now',
 'Can you check this file',
 'You have been selected for a reward',
 'Please send the report by evening',
 'Claim your free voucher today',
 'Exclusive offer just for you Click now',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Claim your free voucher today',
 'Let s have lunch today',
 'Let s have lunch today',
 'Win cash prize now',
 'You have been selected for a reward',
 'Claim your free voucher today',
 'Win cash prize now',
 'Call me when you re free',
 'Win cash prize now',
 'Call me when you re free',
 'Claim your free voucher today',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Let s have lunch today',
 'Call me when you re free',
 'You have been selected for a reward',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Exclusive offer just for you Click now',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'Can you check this file',
 'Let s have lunch today',
 'Please send the report by evening',
 'Let s have lunch today',
 'Call me when you re free',
 'You have been selected for a reward',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'You have been selected for a reward',
 'Claim your free voucher today',
 'Please send the report by evening',
 'Claim your free voucher today',
 'Call me when you re free',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'You have been selected for a reward',
 'You have been selected for a reward',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Claim your free voucher today',
 'Claim your free voucher today',
 'You have been selected for a reward',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Win cash prize now',
 'Win cash prize now',
 'Let s have lunch today',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Let s have lunch today',
 'Hey are we meeting tomorrow',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'Call me when you re free',
 'Win cash prize now',
 'Can you check this file',
 'Claim your free voucher today',
 'Let s have lunch today',
 'Call me when you re free',
 'Can you check this file',
 'Exclusive offer just for you Click now',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Hey are we meeting tomorrow',
 'Claim your free voucher today',
 'Let s have lunch today',
 'Can you check this file',
 'Call me when you re free',
 'Win cash prize now',
 'Win cash prize now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Let s have lunch today',
 'Please send the report by evening',
 'Please send the report by evening',
 'Exclusive offer just for you Click now',
 'Exclusive offer just for you Click now',
 'Congratulations You have won a free ticket Call now',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Exclusive offer just for you Click now',
 'You have been selected for a reward',
 'Can you check this file',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'Call me when you re free',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Claim your free voucher today',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'Can you check this file',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Claim your free voucher today',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'Call me when you re free',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Can you check this file',
 'You have been selected for a reward',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Hey are we meeting tomorrow',
 'Can you check this file',
 'Please send the report by evening',
 'Please send the report by evening',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Exclusive offer just for you Click now',
 'You have been selected for a reward',
 'Win cash prize now',
 'Let s have lunch today',
 'Win cash prize now',
 'Please send the report by evening',
 'Win cash prize now',
 'Call me when you re free',
 'Call me when you re free',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'Can you check this file',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Please send the report by evening',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Call me when you re free',
 'Win cash prize now',
 'Call me when you re free',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Call me when you re free',
 'Can you check this file',
 'Let s have lunch today',
 'Hey are we meeting tomorrow',
 'Claim your free voucher today',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Win cash prize now',
 'Claim your free voucher today',
 'Can you check this file',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Call me when you re free',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Claim your free voucher today',
 'Claim your free voucher today',
 'Claim your free voucher today',
 'Let s have lunch today',
 'Please send the report by evening',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Let s have lunch today',
 'Hey are we meeting tomorrow',
 'Exclusive offer just for you Click now',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'You have been selected for a reward',
 'Let s have lunch today',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'Can you check this file',
 'Claim your free voucher today',
 'Can you check this file',
 'Can you check this file',
 'Claim your free voucher today',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'Hey are we meeting tomorrow',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'Please send the report by evening',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Hey are we meeting tomorrow',
 'Call me when you re free',
 'Win cash prize now',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Call me when you re free',
 'Please send the report by evening',
 'Please send the report by evening',
 'Hey are we meeting tomorrow',
 'Let s have lunch today',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Let s have lunch today',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Can you check this file',
 'Win cash prize now',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Let s have lunch today',
 'Win cash prize now',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Can you check this file',
 'Win cash prize now',
 'Can you check this file',
 'Can you check this file',
 'Please send the report by evening',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Call me when you re free',
 'Exclusive offer just for you Click now',
 'Please send the report by evening',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Can you check this file',
 'Call me when you re free',
 'Call me when you re free',
 'Claim your free voucher today',
 'Call me when you re free',
 'Call me when you re free',
 'Call me when you re free',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Let s have lunch today',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'Please send the report by evening',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Call me when you re free',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Claim your free voucher today',
 'You have been selected for a reward',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Win cash prize now',
 'You have been selected for a reward',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'Claim your free voucher today',
 'You have been selected for a reward',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Win cash prize now',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'Let s have lunch today',
 'Hey are we meeting tomorrow',
 'Please send the report by evening',
 'Win cash prize now',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'You have been selected for a reward',
 'Call me when you re free',
 'Claim your free voucher today',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Hey are we meeting tomorrow',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Claim your free voucher today',
 'Call me when you re free',
 'You have been selected for a reward',
 'Call me when you re free',
 'Can you check this file',
 'Claim your free voucher today',
 'Can you check this file',
 'Congratulations You have won a free ticket Call now',
 'Call me when you re free',
 'Can you check this file',
 'You have been selected for a reward',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'Hey are we meeting tomorrow',
 'Can you check this file',
 'Can you check this file',
 'You have been selected for a reward',
 'Exclusive offer just for you Click now',
 'Win cash prize now',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'Win cash prize now',
 'You have been selected for a reward',
 'Let s have lunch today',
 'Can you check this file',
 'Let s have lunch today',
 'Win cash prize now',
 'Can you check this file',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Exclusive offer just for you Click now',
 'Hey are we meeting tomorrow',
 'Win cash prize now',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Hey are we meeting tomorrow',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Exclusive offer just for you Click now',
 'Exclusive offer just for you Click now',
 'Exclusive offer just for you Click now',
 'Call me when you re free',
 'Let s have lunch today',
 'Win cash prize now',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'Can you check this file',
 'Can you check this file',
 'Let s have lunch today',
 'Win cash prize now',
 'Call me when you re free',
 'Hey are we meeting tomorrow',
 'Call me when you re free',
 'Congratulations You have won a free ticket Call now',
 'Claim your free voucher today',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Exclusive offer just for you Click now',
 'Claim your free voucher today',
 'Please send the report by evening',
 'Win cash prize now',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Congratulations You have won a free ticket Call now',
 'Please send the report by evening',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'Exclusive offer just for you Click now',
 'Let s have lunch today',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'Please send the report by evening',
 'Hey are we meeting tomorrow',
 'Claim your free voucher today',
 'Win cash prize now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Claim your free voucher today',
 'Win cash prize now',
 'You have been selected for a reward',
 'Can you check this file',
 'Please send the report by evening',
 'You have been selected for a reward',
 'You have been selected for a reward',
 'Call me when you re free',
 'Let s have lunch today',
 'Win cash prize now',
 'Claim your free voucher today',
 'Let s have lunch today',
 'Win cash prize now',
 'Let s have lunch today',
 'Can you check this file',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Exclusive offer just for you Click now',
 'Please send the report by evening',
 'Please send the report by evening',
 'Congratulations You have won a free ticket Call now',
 'Can you check this file',
 'Can you check this file',
 'Hey are we meeting tomorrow',
 'Hey are we meeting tomorrow',
 'Exclusive offer just for you Click now',

In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess ### Convert a document into a list of lowercase tokens, ignoring tokens that are too short or too long

In [13]:
words =[]
for sent in corpus:
    sent_token =sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [14]:
words

[['please', 'send', 'the', 'report', 'by', 'evening'],
 ['can', 'you', 'check', 'this', 'file'],
 ['can', 'you', 'check', 'this', 'file'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['let', 'have', 'lunch', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['let', 'have', 'lunch', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['can', 'you', 'check', 'this', 'file'],
 ['let', 'have', 'lunch', 'today'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['can', 'you', 'check', 'this', 'file'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['can', 'you', 'check', 'this', 'file'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['win', 'cash', 'prize', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['win', 'cash', 'prize', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['let', 'have', 'lunch', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['can', 'you', 'check', 'this', 'file'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['win', 'cash', 'prize', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['can', 'you', 'check', 'this', 'file'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['win', 'cash', 'prize', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['can', 'you', 'check', 'this', 'file'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['win', 'cash', 'prize', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['can', 'you', 'check', 'this', 'file'],
 ['win', 'cash', 'prize', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['can', 'you', 'check', 'this', 'file'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['can', 'you', 'check', 'this', 'file'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['win', 'cash', 'prize', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['win', 'cash', 'prize', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['can', 'you', 'check', 'this', 'file'],
 ['let', 'have', 'lunch', 'today'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['win', 'cash', 'prize', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['let', 'have', 'lunch', 'today'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['let', 'have', 'lunch', 'today'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['can', 'you', 'check', 'this', 'file'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['win', 'cash', 'prize', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['can', 'you', 'check', 'this', 'file'],
 ['win', 'cash', 'prize', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['can', 'you', 'check', 'this', 'file'],
 ['win', 'cash', 'prize', 'now'],
 ['can', 'you', 'check', 'this', 'file'],
 ['can', 'you', 'check', 'this', 'file'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['can', 'you', 'check', 'this', 'file'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['win', 'cash', 'prize', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['call', 'me', 'when', 'you', 're', 'free'],

In [15]:
import gensim

In [16]:
model=gensim.models.Word2Vec(words)

In [17]:
## Get all the vocab
model.wv.index_to_key

['you',
 'have',
 'now',
 'free',
 'today',
 'call',
 'for',
 'lunch',
 'let',
 'file',
 'this',
 'check',
 'can',
 'voucher',
 'your',
 'claim',
 'prize',
 'cash',
 'win',
 'ticket',
 'won',
 'congratulations',
 'click',
 'just',
 'offer',
 'exclusive',
 'tomorrow',
 'meeting',
 'we',
 'are',
 'hey',
 're',
 'when',
 'me',
 'reward',
 'selected',
 'been',
 'evening',
 'by',
 'report',
 'the',
 'send',
 'please']

In [18]:
model.corpus_count

5572

In [19]:
model.epochs

5

In [20]:
model.wv.similar_by_word('report')

[('send', 0.9984312653541565),
 ('evening', 0.9980818629264832),
 ('by', 0.9979560971260071),
 ('please', 0.9976500272750854),
 ('the', 0.9976310729980469),
 ('we', 0.4917351007461548),
 ('meeting', 0.48544904589653015),
 ('hey', 0.4834009110927582),
 ('tomorrow', 0.4785919785499573),
 ('are', 0.4735286235809326)]

In [21]:
model.wv['report'].shape

(100,)

In [22]:
words[0]

['please', 'send', 'the', 'report', 'by', 'evening']

In [23]:
import numpy as np

In [24]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent =[word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [25]:
from tqdm import tqdm

In [26]:
# Apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|██████████| 5572/5572 [00:00<00:00, 64510.48it/s]

In [27]:
X

[array([-0.25461656, -0.07331955, -0.4633806 , -0.63977   ,  0.07634231,
        -0.42980227,  0.09434512, -0.09487925,  0.12828323, -0.2729636 ,
         0.12713458, -0.24168712, -0.4633734 ,  0.22808085, -0.16224827,
        -0.5752127 ,  0.33512673,  0.20968227,  0.07804129, -0.08187891,
         0.24554731,  0.12398487,  0.6309499 , -0.45347503,  0.6076395 ,
         0.20151077,  0.10384661, -0.03536486, -0.332904  , -0.00766904,
         0.4332116 , -0.03193435,  0.28335065, -0.6970453 , -0.06206281,
         0.3279471 , -0.28644636,  0.14145671, -0.23801677, -0.36956057,
        -0.2235082 , -0.10219637,  0.15998487, -0.32705116, -0.05291256,
        -0.5639821 ,  0.01560055, -0.4133457 ,  0.2543101 ,  0.35088634,
         0.28881156,  0.23814376,  0.1677181 ,  0.3033894 , -0.19244462,
        -0.01644522,  0.24194169, -0.10231251, -0.639069  , -0.04979542,
         0.24953987, -0.28505278,  0.21318066,  0.23450786, -0.20303805,
         0.34603444, -0.73242664, -0.12470893, -0.75131154,  0.77916473,
         0.00830496,  0.31683245,  0.45754877,  0.1508836 ,  0.37908587,
        -0.11379173, -0.08961117,  0.485746  , -0.22546577, -0.12015831,
        -0.3769637 ,  0.18347418, -0.57491374,  0.10348367,  0.03744189,
        -0.1599787 ,  0.4077077 ,  0.0951823 , -0.27888447, -0.12536724,
         0.23902352, -0.12715667,  0.18048567, -0.5316971 , -0.04799945,
         0.1336085 , -0.18278678, -0.4428594 , -0.39611006, -0.27724633],
       dtype=float32),
 array([ 0.1477429 , -0.07057855,  0.17113039,  0.01234812, -0.19322321,
        -0.4033386 ,  0.0193417 ,  0.63899815, -0.11074529, -0.5423011 ,
         0.3215131 , -0.27915588, -0.04121952,  0.1234353 , -0.0575542 ,
        -0.16327402,  0.33101183, -0.22612283, -0.02938244, -0.7387818 ,
        -0.07724608, -0.01966004,  0.32812923, -0.16204908, -0.03238687,
        -0.08581144, -0.4036847 ,  0.40323114, -0.08056976,  0.19888107,
         0.05609748, -0.14576402,  0.38750836, -0.13460644, -0.19912799,
         0.12909979,  0.10179044, -0.17851745, -0.17235413, -0.155997  ,
        -0.23288289,  0.07092246, -0.2501937 ,  0.00248958, -0.15286705,
        -0.40363207,  0.06433846, -0.02056265, -0.06334077,  0.5313303 ,
         0.10807518, -0.09744984, -0.10988092,  0.15017112,  0.06080288,
        -0.21367355,  0.02913774, -0.00889986,  0.09820507,  0.17205213,
        -0.3285446 , -0.179106  ,  0.42759052, -0.04754474, -0.53421855,
         0.38895386, -0.03866905, -0.1257523 , -0.49384594,  0.1638972 ,
         0.24035497,  0.653156  ,  0.11022754, -0.05241987,  0.28148752,
         0.11786516,  0.16746776, -0.0358703 , -0.21320495, -0.01633271,
        -0.14764753,  0.30850926, -0.07089096,  0.5030631 , -0.14684536,
        -0.09216831, -0.03045714, -0.14871082,  0.26825586,  0.51819706,
         0.16641052,  0.03024281,  0.08433952, -0.05408841,  0.4521435 ,
        -0.14987609, -0.01420031, -0.13043614,  0.20622274,  0.01826736],
       dtype=float32),
 array([ 0.1477429 , -0.07057855,  0.17113039,  0.01234812, -0.19322321,
        -0.4033386 ,  0.0193417 ,  0.63899815, -0.11074529, -0.5423011 ,
         0.3215131 , -0.27915588, -0.04121952,  0.1234353 , -0.0575542 ,
        -0.16327402,  0.33101183, -0.22612283, -0.02938244, -0.7387818 ,
        -0.07724608, -0.01966004,  0.32812923, -0.16204908, -0.03238687,
        -0.08581144, -0.4036847 ,  0.40323114, -0.08056976,  0.19888107,
         0.05609748, -0.14576402,  0.38750836, -0.13460644, -0.19912799,
         0.12909979,  0.10179044, -0.17851745, -0.17235413, -0.155997  ,
        -0.23288289,  0.07092246, -0.2501937 ,  0.00248958, -0.15286705,
        -0.40363207,  0.06433846, -0.02056265, -0.06334077,  0.5313303 ,
         0.10807518, -0.09744984, -0.10988092,  0.15017112,  0.06080288,
        -0.21367355,  0.02913774, -0.00889986,  0.09820507,  0.17205213,
        -0.3285446 , -0.179106  ,  0.42759052, -0.04754474, -0.53421855,
         0.38895386, -0.03866905, -0.1257523 , -0.49384594,  0.1638972 ,
         0.24035497,  0.653156  ,  0.11022754, -0.05241987,  0.28148752,
         0.11786516,  0.16746776, -0.0358703 , -0.21320495, -0.01633271,
        -0.14764753,  0.30850926, -0.07089096,  0.5030631 , -0.14684536,
        -0.09216831, -0.03045714, -0.14871082,  0.26825586,  0.51819706,
         0.16641052,  0.03024281,  0.08433952, -0.05408841,  0.4521435 ,
        -0.14987609, -0.01420031, -0.13043614,  0.20622274,  0.01826736],
       dtype=float32),
 array([-0.09519037,  0.05834965,  0.05220391,  0.20802474, -0.26449966,
        -0.2857922 ,  0.06204711,  0.47916806,  0.04464178, -0.60317445,
         0.387041  ,  0.07831832, -0.06868919,  0.16622074,  0.1502197 ,
        -0.1767361 ,  0.24729301, -0.2935446 , -0.21342254, -0.30989948,
        -0.2190178 ,  0.05709247,  0.42760813,  0.10582951,  0.10390422,
        -0.03607115,  0.09460171,  0.1693974 , -0.13554306,  0.5302325 ,
         0.16795874, -0.58642167,  0.19802433, -0.7235732 , -0.12109789,
         0.42584476,  0.12769239, -0.1462857 ,  0.06292112, -0.08315589,
         0.01830639, -0.29536578, -0.21334983,  0.08698245,  0.5040336 ,
        -0.18335046, -0.23450245,  0.10132974, -0.04749347,  0.09398248,
         0.16031826,  0.01557614, -0.17597169, -0.16377915, -0.21849678,
         0.06478687,  0.23657168,  0.02176688, -0.13457637,  0.03946113,
        -0.14809816, -0.06362732,  0.34643462, -0.03539731,  0.04833443,
         0.2633231 ,  0.1792236 ,  0.31905252, -0.36748752,  0.04523277,
         0.2808867 ,  0.32924235,  0.00804457,  0.07716617,  0.41199622,
         0.07754778, -0.12605233,  0.2409721 ,  0.08185491, -0.02139489,
         0.01085414, -0.3366703 ,  0.27729782, -0.10499796,  0.06134156,
         0.01082027,  0.16801094, -0.20404623,  0.18878073,  0.46796286,
         0.03184534,  0.04301129,  0.00281517, -0.27958748,  0.3507693 ,
        -0.05351781,  0.01391216, -0.21148543,  0.21884382, -0.14352416],
       dtype=float32),
 array([-0.253883  ,  0.29717663,  0.01047618,  0.22098097, -0.06951043,
        -0.13686913,  0.17032349,  0.15402645, -0.11270004, -0.20023957,
         0.21929692, -0.15286106, -0.08589742,  0.12363978,  0.07645558,
        -0.06627776,  0.24000368,  0.14986806, -0.23317005, -0.25537598,
         0.17810299,  0.13402976,  0.44695508, -0.02227403, -0.06670894,
         0.13592881, -0.0149128 ,  0.04653531, -0.2205794 ,  0.12325031,
         0.19615422, -0.25281203,  0.26619762, -0.50224984, -0.00993473,
         0.15046643,  0.03405634,  0.08547969, -0.13346761,  0.06354415,
         0.19355565, -0.18996963, -0.13494912,  0.11538436,  0.35670218,
        -0.03185648, -0.18206671, -0.12271866,  0.2640028 , -0.03212197,
         0.05121364, -0.05256967, -0.03777555, -0.24730004, -0.12126832,
         0.0411225 ,  0.27975   ,  0.03281789,  0.02742487, -0.04044141,
        -0.05577188, -0.11326474,  0.20141637, -0.0009882 , -0.03491106,
         0.26933983, -0.0017018 ,  0.38460702, -0.25529173,  0.10812297,
        -0.03174061,  0.06632017,  0.20279466,  0.22099662,  0.23688373,
         0.10539766,  0.0294348 ,  0.10966464, -0.02951773, -0.1750927 ,
        -0.5077614 , -0.2574008 ,  0.09495041,  0.05816817,  0.01165142,
        -0.16641106,  0.3406448 , -0.05600388,  0.05153844,  0.05670668,
         0.05967122,  0.06500709,  0.10145401, -0.19832858,  0.14309274,
         0.05220114,  0.2325072 ,  0.04692272, -0.10487176,  0.10590181],
       dtype=float32),
 array([ 0.1477429 , -0.07057855,  0.17113039,  0.01234812, -0.19322321,
        -0.4033386 ,  0.0193417 ,  0.63899815, -0.11074529, -0.5423011 ,
         0.3215131 , -0.27915588, -0.04121952,  0.1234353 , -0.0575542 ,
        -0.16327402,  0.33101183, -0.22612283, -0.02938244, -0.7387818 ,
        -0.07724608, -0.01966004,  0.32812923, -0.16204908, -0.03238687,
        -0.08581144, -0.4036847 ,  0.40323114, -0.08056976,  0.19888107,
         0.05609748, -0.14576402,  0.38750836, -0.13460644, -0.19912799,
         0.12909979,  0.10179044, -0.17851745, -0.17235413, -0.155997  ,
        -0.23288289,  0.07092246, -0.2501937 ,  0.00248958, -0.15286705,
        -0.40363207,  0.06433846, -0.02056265, -0.06334077,  0.5313303 ,
         0.10807518, -0.09744984, -0.10988092,  0.15017112,  0.06080288,
        -0.21367355,  0.02913774, -0.00889986,  0.09820507,  0.17205213,
        -0.3285446 , -0.179106  ,  0.42759052, -0.04754474, -0.53421855,
         0.38895386, -0.03866905, -0.1257523 , -0.49384594,  0.1638972 ,
         0.24035497,  0.653156  ,  0.11022754, -0.05241987,  0.28148752,
         0.11786516,  0.16746776, -0.0358703 , -0.21320495, -0.01633271,
        -0.14764753,  0.30850926, -0.07089096,  0.5030631 , -0.14684536,
        -0.09216831, -0.03045714, -0.14871082,  0.26825586,  0.51819706,
         0.16641052,  0.03024281,  0.08433952, -0.05408841,  0.4521435 ,
        -0.14987609, -0.01420031, -0.13043614,  0.20622274,  0.01826736],
       dtype=float32),
 array([-0.25461656, -0.07331955, -0.4633806 , -0.63977   ,  0.07634231,
        -0.42980227,  0.09434512, -0.09487925,  0.12828323, -0.2729636 ,
         0.12713458, -0.24168712, -0.4633734 ,  0.22808085, -0.16224827,
        -0.5752127 ,  0.33512673,  0.20968227,  0.07804129, -0.08187891,
         0.24554731,  0.12398487,  0.6309499 , -0.45347503,  0.6076395 ,
         0.20151077,  0.10384661, -0.03536486, -0.332904  , -0.00766904,
         0.4332116 , -0.03193435,  0.28335065, -0.6970453 , -0.06206281,
         0.3279471 , -0.28644636,  0.14145671, -0.23801677, -0.36956057,
        -0.2235082 , -0.10219637,  0.15998487, -0.32705116, -0.05291256,
        -0.5639821 ,  0.01560055, -0.4133457 ,  0.2543101 ,  0.35088634,
         0.28881156,  0.23814376,  0.1677181 ,  0.3033894 , -0.19244462,
        -0.01644522,  0.24194169, -0.10231251, -0.639069  , -0.04979542,
         0.24953987, -0.28505278,  0.21318066,  0.23450786, -0.20303805,
         0.34603444, -0.73242664, -0.12470893, -0.75131154,  0.77916473,
         0.00830496,  0.31683245,  0.45754877,  0.1508836 ,  0.37908587,
        -0.11379173, -0.08961117,  0.485746  , -0.22546577, -0.12015831,
        -0.3769637 ,  0.18347418, -0.57491374,  0.10348367,  0.03744189,
        -0.1599787 ,  0.4077077 ,  0.0951823 , -0.27888447, -0.12536724,
         0.23902352, -0.12715667,  0.18048567, -0.5316971 , -0.04799945,
         0.1336085 , -0.18278678, -0.4428594 , -0.39611006, -0.27724633],
       dtype=float32),
 array([ 0.11605143,  0.07953175,  0.22504096,  0.23095308, -0.46112442,
        -0.2636233 ,  0.18903375,  0.49601316, -0.1387515 , -0.38988897,
         0.25200996, -0.14271854,  0.14139012,  0.46113166,  0.00254111,
         0.05557602,  0.23372875,  0.37591922, -0.29372782, -0.42268288,
         0.14983483,  0.04812282,  0.09989925, -0.09932491, -0.13384624,
        -0.05275907,  0.01073085, -0.06115467, -0.17058988,  0.08218919,
         0.19522561, -0.09725621,  0.19097708, -0.5130604 , -0.15321332,
         0.19717242,  0.24921227, -0.2775686 , -0.19734691, -0.08122217,
         0.08352872, -0.06921613,  0.00802809, -0.32171258,  0.32022098,
        -0.03802868, -0.06053512, -0.12099999,  0.23170282,  0.10362682,
         0.04164009, -0.1505732 , -0.416634  , -0.14893149,  0.16450457,
         0.04661566,  0.23891337,  0.0054005 ,  0.05322428, -0.20672607,
        -0.21449657, -0.09198534,  0.13794874, -0.10587779, -0.1604161 ,
         0.59589547, -0.02042796, -0.04494244, -0.38794076,  0.1422474 ,
         0.11056685,  0.19720168,  0.12677146,  0.08118851,  0.37858918,
         0.18230444,  0.2135091 ,  0.02285551, -0.13885148,  0.23597057,
        -0.25227827, -0.08850122, -0.00523022,  0.26993084,  0.01897213,
        -0.23563184,  0.16776435, -0.10290265,  0.20055382,  0.524849  ,
        -0.0528689 , -0.09305177,  0.16537197, -0.16874784,  0.21022618,
         0.05435786,  0.13583572,  0.01307422, -0.02905049,  0.17167445],
       dtype=float32),
 array([ 0.17778827, -0.02687424,  0.05809692,  0.00718282,  0.2539274 ,
        -0.19208412,  0.18039174,  0.51761115, -0.29828784, -0.29083413,
        -0.27548504, -0.31680313,  0.23516583,  0.394516  ,  0.18716133,
        -0.08031937,  0.21355242,  0.24616112, -0.01500025, -0.47557712,
         0.21311943, -0.05749313, -0.17008749, -0.20033535,  0.08192209,
         0.03025349, -0.06546138, -0.05098628, -0.02502975,  0.0214696 ,
         0.36640275, -0.17251039, -0.3576619 , -0.46735942, -0.05834533,
         0.23137727,  0.19295166,  0.09011722, -0.01185456, -0.30634972,
         0.08840378, -0.3842509 ,  0.09129473,  0.23523149,  0.16332588,
        -0.16598977, -0.32126826, -0.26593778,  0.25124818,  0.04940275,
         0.12442996, -0.12813237, -0.10179339, -0.05946011,  0.0164388 ,
         0.2493257 ,  0.07728539, -0.1488907 , -0.17649676,  0.07061811,
         0.04133886, -0.03156296,  0.25925767,  0.29518023, -0.04682523,
         0.53426844,  0.01674943,  0.2024773 , -0.06128431,  0.18917245,
         0.23618816,  0.06069347,  0.16935523,  0.0823906 ,  0.34185642,
         0.04072047,  0.31610903,  0.35227823,  0.0204546 ,  0.01364218,
        -0.18894304, -0.05871363, -0.13493472, -0.01646048,  0.07993741,
         0.04761966,  0.09936354, -0.04125448,  0.16026832,  0.04045621,
         0.32117203,  0.02585458,  0.3465382 , -0.00349064,  0.2810982 ,
         0.20124176,  0.01446778, -0.19042525,  0.10490626, -0.02543165],
       dtype=float32),
 array([-0.01926546,  0.19884826,  0.17584701,  0.3295712 , -0.26367864,
        -0.19289345,  0.15156874,  0.53763866, -0.09573898, -0.53382576,
         0.2638391 , -0.01126741,  0.12673014,  0.25629508,  0.21859631,
        -0.10517703,  0.2666596 ,  0.01342435, -0.3545673 , -0.37759346,
        -0.09525453,  0.03774067,  0.18230236,  0.04460409, -0.05191939,
        -0.00511205,  0.08524765,  0.03285962, -0.11626191,  0.38160208,
         0.22581038, -0.5546017 ,  0.05792959, -0.6647925 , -0.14376374,
         0.3616894 ,  0.21981522, -0.11838833,  0.00248911, -0.10317662,
         0.15185231, -0.23599352, -0.16232577,  0.14697683,  0.43510294,
        -0.12348057, -0.2668821 , -0.04955428,  0.0842813 ,  0.05362011,
         0.1475157 , -0.1327181 , -0.30657828, -0.25477952, -0.15979448,
         0.17121826,  0.28145805, -0.00852018, -0.07391361, -0.07973007,
        -0.14274897,  0.01414663,  0.30633634, -0.06292475,  0.01019617,
         0.50238353,  0.21419056,  0.30713075, -0.29988986, -0.00556766,
         0.23769377,  0.24634849,  0.0559101 ,  0.09972313,  0.37267083,
         0.20112468,  0.09082912,  0.2747532 ,  0.02005709,  0.00800095,
        -0.1935128 , -0.29623765,  0.25341794, -0.06806847,  0.05257637,
        -0.03099142,  0.20112047, -0.22696908,  0.1592025 ,  0.3844266 ,
         0.04477867,  0.02939682,  0.06488524, -0.1157094 ,  0.35150078,
        -0.00942949,  0.0674901 , -0.09257931,  0.13106053,  0.0085611 ],
       dtype=float32),
 array([ 0.11605143,  0.07953175,  0.22504096,  0.23095308, -0.46112442,
        -0.2636233 ,  0.18903375,  0.49601316, -0.1387515 , -0.38988897,
         0.25200996, -0.14271854,  0.14139012,  0.46113166,  0.00254111,
         0.05557602,  0.23372875,  0.37591922, -0.29372782, -0.42268288,
         0.14983483,  0.04812282,  0.09989925, -0.09932491, -0.13384624,
        -0.05275907,  0.01073085, -0.06115467, -0.17058988,  0.08218919,
         0.19522561, -0.09725621,  0.19097708, -0.5130604 , -0.15321332,
         0.19717242,  0.24921227, -0.2775686 , -0.19734691, -0.08122217,
         0.08352872, -0.06921613,  0.00802809, -0.32171258,  0.32022098,
        -0.03802868, -0.06053512, -0.12099999,  0.23170282,  0.10362682,
         0.04164009, -0.1505732 , -0.416634  , -0.14893149,  0.16450457,
         0.04661566,  0.23891337,  0.0054005 ,  0.05322428, -0.20672607,
        -0.21449657, -0.09198534,  0.13794874, -0.10587779, -0.1604161 ,
         0.59589547, -0.02042796, -0.04494244, -0.38794076,  0.1422474 ,
         0.11056685,  0.19720168,  0.12677146,  0.08118851,  0.37858918,
         0.18230444,  0.2135091 ,  0.02285551, -0.13885148,  0.23597057,
        -0.25227827, -0.08850122, -0.00523022,  0.26993084,  0.01897213,
        -0.23563184,  0.16776435, -0.10290265,  0.20055382,  0.524849  ,
        -0.0528689 , -0.09305177,  0.16537197, -0.16874784,  0.21022618,
         0.05435786,  0.13583572,  0.01307422, -0.02905049,  0.17167445],
       dtype=float32),
 array([-0.09519037,  0.05834965,  0.05220391,  0.20802474, -0.26449966,
        -0.2857922 ,  0.06204711,  0.47916806,  0.04464178, -0.60317445,
         0.387041  ,  0.07831832, -0.06868919,  0.16622074,  0.1502197 ,
        -0.1767361 ,  0.24729301, -0.2935446 , -0.21342254, -0.30989948,
        -0.2190178 ,  0.05709247,  0.42760813,  0.10582951,  0.10390422,
        -0.03607115,  0.09460171,  0.1693974 , -0.13554306,  0.5302325 ,
         0.16795874, -0.58642167,  0.19802433, -0.7235732 , -0.12109789,
         0.42584476,  0.12769239, -0.1462857 ,  0.06292112, -0.08315589,
         0.01830639, -0.29536578, -0.21334983,  0.08698245,  0.5040336 ,
        -0.18335046, -0.23450245,  0.10132974, -0.04749347,  0.09398248,
         0.16031826,  0.01557614, -0.17597169, -0.16377915, -0.21849678,
         0.06478687,  0.23657168,  0.02176688, -0.13457637,  0.03946113,
        -0.14809816, -0.06362732,  0.34643462, -0.03539731,  0.04833443,
         0.2633231 ,  0.1792236 ,  0.31905252, -0.36748752,  0.04523277,
         0.2808867 ,  0.32924235,  0.00804457,  0.07716617,  0.41199622,
         0.07754778, -0.12605233,  0.2409721 ,  0.08185491, -0.02139489,
         0.01085414, -0.3366703 ,  0.27729782, -0.10499796,  0.06134156,
         0.01082027,  0.16801094, -0.20404623,  0.18878073,  0.46796286,
         0.03184534,  0.04301129,  0.00281517, -0.27958748,  0.3507693 ,
        -0.05351781,  0.01391216, -0.21148543,  0.21884382, -0.14352416],
       dtype=float32),
 array([-0.39063674,  0.39428893, -0.17385906,  0.1041498 ,  0.04484924,
        -0.24092117,  0.05338325,  0.18502149, -0.03230848, -0.2667799 ,
         0.2104567 , -0.11951576, -0.31995234, -0.02078629,  0.08096875,
        -0.13340276,  0.3621032 , -0.08741586, -0.08041125, -0.2841497 ,
         0.13995564,  0.1635309 ,  0.5780433 ,  0.13640578, -0.0137311 ,
         0.20939676, -0.06629495,  0.18802509, -0.14320043,  0.20893553,
         0.205694  , -0.38227504,  0.25211322, -0.6521614 ,  0.02681298,
         0.17740646,  0.09856804,  0.16498522, -0.14945991,  0.18313625,
         0.20701244, -0.3700927 , -0.14878875,  0.3227269 ,  0.44567433,
        -0.11967795, -0.31708604, -0.13566718,  0.20981903, -0.08602428,
         0.14054993,  0.06505309,  0.08624505, -0.16444731, -0.3457782 ,
         0.02214672,  0.39034247,  0.00391348, -0.06923904,  0.16891731,
         0.02201184, -0.17522809,  0.36814   ,  0.17860846,  0.14195351,
         0.11529511,  0.07982246,  0.5433229 , -0.243189  ,  0.1424445 ,
        -0.06024999,  0.05690091,  0.13229416,  0.17020053,  0.36672452,
         0.10165477, -0.0750275 ,  0.3508411 ,  0.07961623, -0.30098206,
        -0.49334174, -0.33830237,  0.19953303, -0.02761164, -0.04277892,
        -0.02175791,  0.43304387,  0.02494509,  0.04680985, -0.03136376,
         0.17160714,  0.1610467 ,  0.07349236, -0.30665055,  0.18701394,
        -0.07546316,  0.30114847, -0.01746143, -0.06602123,  0.15367386],
       dtype=float32),
 array([ 0.1477429 , -0.07057855,  0.17113039,  0.01234812, -0.19322321,
        -0.4033386 ,  0.0193417 ,  0.63899815, -0.11074529, -0.5423011 ,
         0.3215131 , -0.27915588, -0.04121952,  0.1234353 , -0.0575542 ,
        -0.16327402,  0.33101183, -0.22612283, -0.02938244, -0.7387818 ,
        -0.07724608, -0.01966004,  0.32812923, -0.16204908, -0.03238687,
        -0.08581144, -0.4036847 ,  0.40323114, -0.08056976,  0.19888107,
         0.05609748, -0.14576402,  0.38750836, -0.13460644, -0.19912799,
         0.12909979,  0.10179044, -0.17851745, -0.17235413, -0.155997  ,
        -0.23288289,  0.07092246, -0.2501937 ,  0.00248958, -0.15286705,

In [28]:
len(X)

5572

In [29]:
X_new = np.array(X)

In [30]:
X_new

array([[-0.25461656, -0.07331955, -0.4633806 , ..., -0.4428594 ,
        -0.39611006, -0.27724633],
       [ 0.1477429 , -0.07057855,  0.17113039, ..., -0.13043614,
         0.20622274,  0.01826736],
       [ 0.1477429 , -0.07057855,  0.17113039, ..., -0.13043614,
         0.20622274,  0.01826736],
       ...,
       [-0.01926546,  0.19884826,  0.17584701, ..., -0.09257931,
         0.13106053,  0.0085611 ],
       [-0.01926546,  0.19884826,  0.17584701, ..., -0.09257931,
         0.13106053,  0.0085611 ],
       [ 0.21624763,  0.06982184,  0.27139404, ..., -0.0985458 ,
         0.11773439,  0.25103137]], shape=(5572, 100), dtype=float32)

In [31]:
X_new.shape

(5572, 100)

In [37]:
X_new[0].reshape(1,-1).shape

(1, 100)

In [41]:
df = pd.DataFrame()
rows =[]
for i in range(0,len(X_new)):
    rows.append(pd.DataFrame(X_new[i].reshape(1,-1)))
df =pd.concat(rows,ignore_index=True)

In [42]:
df.shape

(5572, 100)

In [43]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.254617,-0.073320,-0.463381,-0.639770,0.076342,-0.429802,0.094345,-0.094879,0.128283,-0.272964,...,0.239024,-0.127157,0.180486,-0.531697,-0.047999,0.133609,-0.182787,-0.442859,-0.396110,-0.277246
1,0.147743,-0.070579,0.171130,0.012348,-0.193223,-0.403339,0.019342,0.638998,-0.110745,-0.542301,...,0.166411,0.030243,0.084340,-0.054088,0.452143,-0.149876,-0.014200,-0.130436,0.206223,0.018267
2,0.147743,-0.070579,0.171130,0.012348,-0.193223,-0.403339,0.019342,0.638998,-0.110745,-0.542301,...,0.166411,0.030243,0.084340,-0.054088,0.452143,-0.149876,-0.014200,-0.130436,0.206223,0.018267
3,-0.095190,0.058350,0.052204,0.208025,-0.264500,-0.285792,0.062047,0.479168,0.044642,-0.603174,...,0.031845,0.043011,0.002815,-0.279587,0.350769,-0.053518,0.013912,-0.211485,0.218844,-0.143524
4,-0.253883,0.297177,0.010476,0.220981,-0.069510,-0.136869,0.170323,0.154026,-0.112700,-0.200240,...,0.059671,0.065007,0.101454,-0.198329,0.143093,0.052201,0.232507,0.046923,-0.104872,0.105902

In [33]:
### Dependent Features
## O/P Features
y =pd.get_dummies(messages['label'])
y=y.iloc[:,0].values
y = messages['label'].map({'ham':0,'spam':1}).values

In [44]:
y

array([0, 0, 0, ..., 1, 1, 1], shape=(5572,))

In [45]:
y.shape

(5572,)

In [46]:
## Independent Feature
X =df

In [47]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [49]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
3988,0.147743,-0.070579,0.171130,0.012348,-0.193223,-0.403339,0.019342,0.638998,-0.110745,-0.542301,...,0.166411,0.030243,0.084340,-0.054088,0.452143,-0.149876,-0.014200,-0.130436,0.206223,0.018267
3922,-0.254617,-0.073320,-0.463381,-0.639770,0.076342,-0.429802,0.094345,-0.094879,0.128283,-0.272964,...,0.239024,-0.127157,0.180486,-0.531697,-0.047999,0.133609,-0.182787,-0.442859,-0.396110,-0.277246
4021,-0.114956,-0.038377,-0.414197,0.342888,0.222253,0.107734,0.451521,-0.043613,-0.191206,0.253215,...,0.265863,0.226658,0.165335,-0.427779,0.254743,0.048516,-0.022255,-0.368909,-0.073423,0.018925
953,-0.019265,0.198848,0.175847,0.329571,-0.263679,-0.192893,0.151569,0.537639,-0.095739,-0.533826,...,0.044779,0.029397,0.064885,-0.115709,0.351501,-0.009429,0.067490,-0.092579,0.131061,0.008561
681,-0.019265,0.198848,0.175847,0.329571,-0.263679,-0.192893,0.151569,0.537639,-0.095739,-0.533826,...,0.044779,0.029397,0.064885,-0.115709,0.351501,-0.009429,0.067490,-0.092579,0.131061,0.008561

In [51]:
y_train

array([0, 0, 0, ..., 1, 0, 0], shape=(4457,))

In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier =RandomForestClassifier()

In [54]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [53]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [55]:
y_pred = classifier.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

1.0

In [57]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       570
           1       1.00      1.00      1.00       545

    accuracy                           1.00      1115
   macro avg       1.00      1.00      1.00      1115
weighted avg       1.00      1.00      1.00      1115